### ISSUE TITLE
Make Build One Step

### ISSUE THREAD

**Issue by ryan-berger** [meraki/dashboard-api-go#14]
**Is your feature request related to a problem? Please describe.**
Currently while editing the dashboard templates or regenerating the library with newer specs, it can take a lot of setup and teardown.

**Describe the solution you'd like**
It would be a good idea to create a Makefile that will take care of the building and code generation for us. Having to run through the commands and clean things up inside the client/ directory is pretty annoying for small changes.

**Describe alternatives you've considered**
We could theoretically make the template a separate repo and vendor in the OpenAPI spec, but I think for now it would be best to have a Makefile that runs through all the commands inside of the README in the client/ directory.

**Comment by iamdexterpark** [comment]
That's a great suggestion. Using a Makefile to automate the build process will undoubtedly help save time. 

An alternative worth considering is to leverage a tool like [act](https://github.com/nektos/act) to run GitHub Actions files locally.

By separating the existing "generate.yml" into "check-version.yml," "generate.yml," and "release.yml," we could preserve the triggered workflows and just run our targeted build process locally.

I have had success using this tool with other repositories, and it is potentially a fit here as well.

**Comment by iamdexterpark** [comment]
Added a Makefile and updated docs with detailed instructions.
